objects/Wiki__c.object
<CustomObject>
    <label>Wiki</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WikiMember__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002lOFBEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Wiki Members</relationshipLabel>
        <relationshipName>WikiMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Member</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WikiMembersRemoveController.cls
/** 
* @author dgadola @ 01-21-09
*/

public class WikiMembersRemoveController {
	
	public String idWiki = System.currentPageReference().getParameters().get('id');
	public String removeMemberId = WikiCreateWikiController.removeMemberId;
	public WikiMemberController wmc = new WikiMemberController();

	/**
	* Constructor
	*/
	public WikiMembersRemoveController() {}
	
	/**
	* @return wikiName
	*/
	public String getWikiName() {
		String name;
		if(idWiki != null){
			Wiki__c currentWiki = [select Name from Wiki__c where Id =: idWiki];
			name = currentWiki.Name;
		}
		return name;
	}
	
	/**
	* @return delName
	*/
	public String getDelName() {
		String delName = '';
		if (WikiCreateWikiController.removeMemberId != null 
				&& WikiCreateWikiController.removeMemberId != '') {
			removeMemberId = WikiCreateWikiController.removeMemberId;
			
			delName = [select User__r.Name from WikiMember__c 
						where User__c =: removeMemberId and Wiki__c =: idWiki].User__r.Name;
		}
		return delName;
	}
	
	/**
	* return if the member to remove is the last admin
	*/
	public Boolean getIsLastMemberAdmin() {
		if (WikiCreateWikiController.removeMemberId != null 
				&& WikiCreateWikiController.removeMemberId != '') {
			removeMemberId = WikiCreateWikiController.removeMemberId;
		}
		wmc.setUserId(removeMemberId);
		wmc.setWikiId(idWiki);
		return wmc.isLastMemberAdmin();	 
	}
	

	/**
	* Delete selected member
	*/
	public void removeMember () {
		if (!getIsLastMemberAdmin()) {
			wmc.setUserId(removeMemberId);
			wmc.setWikiId(idWiki);
			wmc.unjoinWiki();	
		}
	}
}