src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Coments (Wiki Page)</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FavoriteWikis__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>FavoriteWikis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Wikis</label>
    <nameField>
        <label>Favorite Wikis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorite Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Wiki__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>WikiProfile__c</referenceTo>
        <relationshipLabel>Wikis (NewMemberProfile)</relationshipLabel>
        <relationshipName>Wikis</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/WikiLink__c.object
<CustomObject>
    <fields>
        <fullName>FromLink__c</fullName>
        <label>FromLink</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wiki Links (FromLink)</relationshipLabel>
        <relationshipName>R00N30000002lOB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ToLink__c</fullName>
        <label>ToLink</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wiki Links</relationshipLabel>
        <relationshipName>R00N30000002lODaEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Link</label>
    <nameField>
        <label>Wiki Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WikiMember__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002lOFBEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiProfile__c</fullName>
        <label>Wiki Profile</label>
        <referenceTo>WikiProfile__c</referenceTo>
        <relationshipLabel>Wiki Members</relationshipLabel>
        <relationshipName>WikiMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Wiki Members</relationshipLabel>
        <relationshipName>WikiMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Member</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WikiProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateWikiPages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateWikiPages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageWikis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageWikis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostWikiComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostWikiComments</label>
        <type>Checkbox</type>
    </fields>
    <label>Wiki Profile</label>
    <nameField>
        <label>Wiki Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WikiRecentlyViewed__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002lOAXEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wikis Recently Viewed</relationshipLabel>
        <relationshipName>R00N30000002lOB5EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Wikis Recently Viewed</relationshipLabel>
        <relationshipName>R00N30000002lO9xEAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Recently Viewed</label>
    <nameField>
        <label>Wiki Recently Vewied Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wikis Recently Viewed</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WikiVersions__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RevisionCount__c</fullName>
        <label>Revision Count</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WikiPageId__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wiki Versions</relationshipLabel>
        <relationshipName>R00N30000002lOEwEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Version</label>
    <nameField>
        <label>Wiki Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Versions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TriggersTest.cls
@isTest private class TriggersTest {

    public static User newUser = new User();		
	public static Wiki__c wiki = new Wiki__c();
	public static WikiPage__c wikiPage = new WikiPage__c();
	public static Comment__c comment = new Comment__c(); 
	public static WikiLink__c wikiLinkFrom = new WikiLink__c(); 
	public static WikiLink__c wikiLinkTo = new WikiLink__c(); 
	public static WikiProfile__c profile = new WikiProfile__c();
	public static WikiMember__c member = new WikiMember__c();
	public static WikiRecentlyViewed__c recentlyViewed = new WikiRecentlyViewed__c();
	public static FavoriteWikis__c favorites = new FavoriteWikis__c();
	public static WikiVersions__c version = new WikiVersions__c();

	public static testMethod void test() 
    {
    	try
    	{
            GenerateEnvironmentTest.gen();

	
            
            newUser = [ SELECT Id, Name FROM User LIMIT 1 ];


            // Create a new Wiki Administrator Profile
            profile.Name = 'Wiki Administrator';
            profile.CreateWikiPages__c = true; 
            profile.ManageWikis__c = true; 
            profile.PostWikiComments__c = true; 
            insert profile;
			

            // Create a new wiki
            wiki.Name = 'Test class Wiki';
            wiki.NewMemberProfile__c = profile.Id;
            wiki.Description__c = 'Discussion description';
            insert wiki;  

            // Create a new WikiPage
            wikiPage.Wiki__c = wiki.Id;
            insert wikiPage;
            
            // Create a new Comment
            comment.WikiPage__c = wikiPage.Id;
            insert comment;
            
            // Crete a new Wiki Link
            wikiLinkFrom.Name= 'test Wiki Link (from)';
            wikiLinkFrom.FromLink__c = wikiPage.Id;
            wikiLinkTo.Name= 'test Wiki Link (to)';
            wikiLinkTo.ToLink__c = wikiPage.Id;
            insert wikiLinkFrom;
            insert wikiLinkTo;
            
            // Create a new Wiki Member
            member.WikiProfile__c = profile.Id;
            member.User__c = newUser.Id;
            member.Wiki__c = wiki.Id;
            insert member;
            
            
			// Wiki Recently Viewed
            recentlyViewed.Name = 'test Wiki Recently Viewed Obj';
            recentlyViewed.User__c = newUser.Id;
            recentlyViewed.Wiki__c = wiki.Id;
            recentlyViewed.WikiPage__c = wikiPage.Id;
            insert recentlyViewed;

           
            // Favorites Wikis Obj
            favorites.Name = wiki.Name;
            favorites.User__c = newUser.Id;
            favorites.Wiki__c = wiki.Id;
            favorites.WikiPage__c = wikiPage.Id;
            insert favorites; 
             
            // Wiki Version
            version.Name = 'Wiki Version test name';
            version.Body__c = 'Is a Long Text Area field';
            version.RevisionCount__c = 1;
            version.WikiPageId__c = wikiPage.Id;
            insert version;

            delete member;
            delete profile;
            delete wikiPage;
            delete wiki;


 
		}
        catch(Exception e)
        {
            throw e;
        }
    }
    
}