src/objects/FavoriteWikis__c.object
<CustomObject>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>FavoriteWikis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Wikis</label>
    <nameField>
        <label>Favorite Wikis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorite Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Wiki__c.object
<CustomObject>
    <label>Wiki</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wiki__c</fullName>
        <label>Wiki</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsWidgetWikiDirectoryControllerTest.cls
@IsTest private class TeamsWidgetWikiDirectoryControllerTest { 
    public static testMethod void testWiki() {
        GenerateEnvironmentTest.gen();
		
		Test.startTest();
        
        TeamsWidgetWikiDirectoryController wiki = new TeamsWidgetWikiDirectoryController();
        UserPermissions userPermissions = new UserPermissions();
        
        userPermissions = new UserPermissions();
		
		wiki.setSidebar(true);
        wiki.getSidebar();        
        
        String idTeam = GenerateEnvironmentTest.wiki.Id;
        wiki.setTeamId(idTeam);
        
        if (wiki.getTeamId() == null) 
            System.assert(true, 'Null Team Id');
        
        if (wiki.getUserPermissions() == null) 
            System.assert(true, 'Null User Permissions');
        
        /* Wikis Class */
      
        WikiPage__c wikiPage = new  WikiPage__c();
        wikiPage = [select id, name, Wiki__c, parent__c, body__c, createdById , createdBy.Name from WikiPage__c where wiki__r.id =:GenerateEnvironmentTest.wiki.Id];
        wikiPage.Name = 'loooooooooooooooooonnnnnnnnnnnnnnnnnnggggggggggggggg';           
        TeamsWidgetWikiDirectoryController.Wikis wikiClass = new TeamsWidgetWikiDirectoryController.Wikis(wikiPage);
        wikiClass.getWikiPage();
        wikiClass.getName();
        wikiClass.getCreatedByName(); 
        
        wiki.getWikis();
        wiki.getWikiPagesCount();
        
        try {
            wiki.refresh();
        }catch (Exception e) {
            System.assert(true, e);
        }
        
        Test.stopTest();
    }
}