trunk/src/objects/WikiSubscription__c.object
<CustomObject>
    <fields>
        <fullName>TeamMemberJoinLeave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberJoinLeave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamMemberStatusUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberStatusUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Wiki__c</referenceTo>
        <relationshipLabel>WikiSubscriptions</relationshipLabel>
        <relationshipName>WikiSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WikiSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiCreatedByMeUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiCreatedByMeUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiNewPage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiNewPage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiPageUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiPageUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>WikiSubscription</label>
    <nameField>
        <label>WikiSubscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSubscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WikiSubscriptionController.cls
public class WikiSubscriptionController {


	public String idTeam = System.currentPageReference().getParameters().get('id');
	Integer subscriptionCount;

	/**
	* Constructor
	*/
	public WikiSubscriptionController () {
		constructMethods(); 
	}
	
	/**
	*@return Integer
	*/
	public Integer getSubscriptionCount () {
		return subscriptionCount;
	}
	
	public WikiSubscription__c subscription = new WikiSubscription__c();
	
	/**
	*@return TeamSubscription__c
	*/
	public WikiSubscription__c getSubscription () {
		return subscription;
	}
	
	/**
	*@param String
	*/
	public void setIdTeam (String idTeam) {
		this.idTeam = idTeam; 
	}
	
	/**
	*@return String
	*/
	public String getIdTeam () {
		return idTeam;
	}

	/**
	* Execute on Construct
	*/
	public void constructMethods () {
		if (idTeam != null) {
			List<WikiSubscription__c> teamSubList = new List<WikiSubscription__c>();
			teamSubList = [select id,    
							TeamMemberStatusUpdated__c,
							TeamMemberJoinLeave__c, 
							WikiCreatedByMeUpdated__c,
							WikiNewPage__c,
							WikiPageUpdated__c,
							Team__c,
							User__c
						from WikiSubscription__c where User__c =:UserInfo.getUserId() and Team__c =: idTeam limit 1];
			if (teamSubList.size() > 0 ) {
				subscription = teamSubList[0];
			}	
			subscriptionCount = teamSubList.size();
		}
	}
	
	/**
	* Save suscription
	*@return PageReference
	*/
	public PageReference saveSubscription () {
		if (subscriptionCount > 0) {
			update 	subscription;	
		}else {
			subscription.Team__c = idTeam;
			subscription.User__c = UserInfo.getUserId();
			insert subscription;
		}
		PageReference pageRef = Page.WikiTeamOverview;
		pageRef.getParameters().put('tid', idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	/**
	* Cancel suscription
	*@return PageReference
	*/
	public PageReference cancelSubscription () {
		PageReference pageRef = Page.WikiTeamOverview;
		pageRef.getParameters().put('tid', idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	/**
	* Delete suscription
	*@return PageReference
	*/
	public PageReference deleteSubscription () {
		if (subscription != null && subscriptionCount > 0 ) 
			delete subscription;
		
		PageReference pageRef = Page.WikiTeamOverview;
		pageRef.getParameters().put('tid', idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
}